version: '3.8'
services:
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173:5173"

  postgres:
    image: postgres
    container_name: postgres
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRESDB_USER
      POSTGRES_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
      POSTGRES_DB: $POSTGRESDB_DATABASE
    ports:
      - "5432:5432"

  gamebuddy:
    env_file: ./.env
    build:
      dockerfile: Dockerfile
    container_name: gamebuddy
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gamebuddy
      SPRING_DATASOURCE_USERNAME: $POSTGRESDB_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update