version: '3.8'
services:
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "5173:5173"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: gamebuddy
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: