server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gamebuddy
  output:
    ansi:
      enabled: always

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.pedroalmeida.gamebuddy: DEBUG
