server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/sampledb # Persistent H2 database URL with a relative file path
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.pedroalmeida.gamebuddy: DEBUG
