server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gamebuddy
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRESDB_PORT}/${POSTGRESDB_DATABASE}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt.secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.web: ERROR
    com.pedroalmeida.gamebuddy: DEBUG