server:
  port: 8080

render:
  env_group: ${gamebuddy-group}

spring:
  application:
    name: gamebuddy
  datasource:
    platform: postgres
    url: ${postgres_url}
    username: ${postgres_user}
    password: ${postgres_password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.pedroalmeida.gamebuddy: DEBUG
