server:
  port: 8080

spring:
  application:
    name: gamebuddy
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/gamebuddy
    username: gamebuddy
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    com.pedroalmeida.gamebuddy: DEBUG