name: Java Gradle CI
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: gamebuddy
          POSTGRES_PASSWORD: password
          POSTGRES_USER: gamebuddy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or your required version

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Push image
        run: |
          docker login --username pedroalmeida96 --password ${{ secrets.GHCR_ACCESS_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/pedroalmeida96/gamebuddy:latest
          docker push ghcr.io/pedroalmeida96/gamebuddy:latest
